# 1. Créez un tableau NumPy contenant les entiers de 1 à 10 (inclus).

In [1]:
import numpy as np #impoter package numpy

a = [*range(1,11)] #creer une liste de 1 à 10

print(np.array(a)) #print le résultat

[ 1  2  3  4  5  6  7  8  9 10]


# 1. Solution bis

In [2]:
import numpy as np
a = [np.arange(1,11)]

print(a)

[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])]


# 2. Créez un tableau NumPy contenant 5 valeurs flottantes générées aléatoirement entre 0 et 1.

In [3]:
import numpy as np

a = [np.random.rand(5)]

print(a)

[array([0.44548735, 0.39236004, 0.99298768, 0.74943955, 0.76487108])]


# 3. Créez une fonction qui prend un tableau NumPy en entrée et renvoie la somme de ses éléments.

In [4]:
import numpy as np

def somme_arr(x):
    y = x.sum()
    return y

array = np.array([(1,2,3),(4,5,6)])

print(array)

print(somme_arr(array))

[[1 2 3]
 [4 5 6]]
21


# 4. Créez une fonction qui prend deux tableaux NumPy en entrée et renvoie le produit scalaire de ces deux tableaux (dot product).

In [5]:
import numpy as np

def mult_array(x,z):
    y = np.dot(x, z, out=None)
    return y

array_1 = np.arange(1,11)

array_2 = np.arange(1,11)

print(mult_array(array_1,array_2))

385


# 5. Créez une fonction qui prend un tableau NumPy en entrée et renvoie un nouveau tableau contenant uniquement les éléments uniques du tableau d'origine.

In [ ]:
import numpy as np

def arr_sort_unique(x):
    y = np.unique(x)
    return y

array = np.array([1,2,3,2,8,5,4,5,6])

print(array)

print(arr_sort_unique(array))

# 6. Créez une fonction qui prend un tableau NumPy en entrée et renvoie un nouveau tableau contenant les éléments triés par ordre croissant.

In [ ]:
import numpy as np

def arr_sort_unique(x):
    y = np.sort(x)
    return y

array = np.array([(1,3,2),(8,1,2)])

print(array)

print(arr_sort_unique(array))

# 7. Créez une fonction qui prend un tableau NumPy en entrée et renvoie la moyenne, la médiane et l'écart type de ses éléments.

In [ ]:
import numpy as np

def arr_sort_unique(x):
    print("For the array :", x)
    y = np.mean(x)
    print("mean of the array =",y)
    z = np.median(x)
    print("median of the array =",z)
    w = np.std(x)
    print("standard deviation of the array =",w)
    return y, z, w

array = np.array([(1,3,2),(8,1,2)])

arr_sort_unique(array)

# 8. Créez une fonction qui prend un tableau NumPy en entrée et renvoie un nouveau tableau où tous les éléments inférieurs à 5 sont remplacés par 0 et tous les éléments supérieurs ou égaux à 5 sont remplacés par 1.

In [ ]:
import numpy as np

def zero_or_one(x):
    y = np.where(x <= 5, 0, 1)
    return y

array = np.array([(9,3,5),(8,1,2)])

print(array)

print(zero_or_one(array))

# 9. Créez un tableau NumPy 2D de taille 3x3 contenant des valeurs entières générées aléatoirement entre 1 et 10.

In [ ]:
import numpy as np

def random_2D_33():
    y = np.random.randint(10, size=(3, 3))
    return y

print(random_2D_33())