Numpy random
Faire un générateur de nombre aléatoire pour le loto et l'euromillion. Attention c’est un tirage aléatoire sans remise (c.a.d que la boule trouvée n’est pas remise en jeu) et tous les chiffres ont la même probabilité d’apparaître.

In [30]:
import numpy as np """Import de la library numpy qui sera appelé np"""

"""Création de la liste de numéros gagnants (num_g), tableau 1D avec 6 numéros random"""

In [31]:
np.random.choice(np.arange(1,50), 5, replace = False)

array([10, 11, 48,  3,  7])

In [32]:
np.random.choice(np.arange(1,10), 1, replace = False)

array([4])

In [49]:
np.random.choice(np.arange(1,51), 5, replace = False)

array([11, 49, 19, 17,  7])

In [34]:
np.random.choice(np.arange(1,12), 2, replace = False)

array([7, 5])