Voici un façon de créer une DataFrame à partir d'un dictionnaire python:

In [2]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "colonne a": [1, 2, 3],
    "colonne b": [6, 7, 8],
    "colonne c": [0, 8, 1]
})

print(df)

   colonne a  colonne b  colonne c
0          1          6          0
1          2          7          8
2          3          8          1


Tester cet objet, accéder au colonne. Itérer l'objet. Afficher le. Récupérer le tableau numpy.  

In [3]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [4]:
df.columns

Index(['colonne a', 'colonne b', 'colonne c'], dtype='object')

In [5]:
for column in df:
    print(df[column].values)

[1 2 3]
[6 7 8]
[0 8 1]


Rajouter une nouvelle colonne.

In [6]:
df['colonne D'] = [1,2,3]

df

colonne a  colonne b  colonne c  colonne D
0          1          6          0          1
1          2          7          8          2
2          3          8          1          3

Renommer une colonne, inplace = True permet de renommer sur le tableau original sans en créer de nouveau.

In [7]:
df.rename(columns = {'colonne D':'colonne d'}, inplace = True)

df

colonne a  colonne b  colonne c  colonne d
0          1          6          0          1
1          2          7          8          2
2          3          8          1          3

Renommer toues le colonne mettant les initial en majuscule (str.title?)

In [8]:
df.rename(str.title,axis='columns',inplace=True)

df

Colonne A  Colonne B  Colonne C  Colonne D
0          1          6          0          1
1          2          7          8          2
2          3          8          1          3

A partir des données fournie, vous devez faire un analyse et synthèse des données. Pour chacun de vos résultats, le code associé doit être fourni (pour prouver votre réponse/analyse). Voici ce qu'ils cherchent à savoir :

In [30]:
df = pd.read_csv("1/reduced_covid_sexe.csv", encoding="latin")
df


Unnamed: 0     hosp  hosp.1  hosp.2     rea  rea.1  rea.2       rad  \
0           sexe      0.0     1.0     2.0     0.0    1.0    2.0       0.0   
1           jour      NaN     NaN     NaN     NaN    NaN    NaN       NaN   
2     2020-03-18   2972.0  1685.0  1248.0   771.0  525.0  239.0     816.0   
3     2020-03-19   4073.0  2256.0  1632.0  1002.0  689.0  284.0    1180.0   
4     2020-03-20   5226.0  2912.0  2134.0  1297.0  905.0  362.0    1587.0   
...          ...      ...     ...     ...     ...    ...    ...       ...   
1106  2023-03-27  13113.0  5950.0  6923.0   728.0  457.0  263.0  861972.0   
1107  2023-03-28  13178.0  6000.0  6943.0   720.0  452.0  261.0  862458.0   
1108  2023-03-29  13184.0  5989.0  6964.0   734.0  456.0  270.0  862962.0   
1109  2023-03-30  13186.0  5953.0  7003.0   732.0  459.0  267.0  863331.0   
1110  2023-03-31  13149.0  5919.0  6997.0   709.0  446.0  258.0  863837.0   

         rad.1     rad.2        dc     dc.1     dc.2  
0          1.0       2.0       0.0      1.0      2.0  
1          NaN       NaN       NaN      NaN      NaN  
2        432.0     379.0     218.0    121.0     96.0  
3        580.0     562.0     327.0    179.0    136.0  
4        777.0     764.0     450.0    250.0    190.0  
...        ...       ...       ...      ...      ...  
1106  421189.0  432745.0  135936.0  77555.0  57324.0  
1107  421407.0  433007.0  135975.0  77575.0  57342.0  
1108  421645.0  433268.0  136009.0  77594.0  57356.0  
1109  421833.0  433447.0  136045.0  77609.0  57376.0  
1110  422089.0  433693.0  136076.0  77630.0  57385.0  

[1111 rows x 13 columns]

Afficher les 15 premières lignes du tableau covid_sexe.csv. (df.head?)

In [31]:
df.head(15)

Unnamed: 0     hosp   hosp.1  hosp.2     rea   rea.1   rea.2     rad  \
0         sexe      0.0      1.0     2.0     0.0     1.0     2.0     0.0   
1         jour      NaN      NaN     NaN     NaN     NaN     NaN     NaN   
2   2020-03-18   2972.0   1685.0  1248.0   771.0   525.0   239.0   816.0   
3   2020-03-19   4073.0   2256.0  1632.0  1002.0   689.0   284.0  1180.0   
4   2020-03-20   5226.0   2912.0  2134.0  1297.0   905.0   362.0  1587.0   
5   2020-03-21   5900.0   3298.0  2401.0  1453.0  1018.0   401.0  1811.0   
6   2020-03-22   6954.0   3906.0  2815.0  1674.0  1176.0   461.0  2117.0   
7   2020-03-23   8673.0   4882.0  3532.0  2080.0  1465.0   569.0  2567.0   
8   2020-03-24  10163.0   5843.0  4149.0  2503.0  1773.0   694.0  3281.0   
9   2020-03-25  12072.0   7064.0  4856.0  2935.0  2127.0   785.0  4085.0   
10  2020-03-26  13879.0   8152.0  5570.0  3351.0  2437.0   888.0  4947.0   
11  2020-03-27  15701.0   9288.0  6248.0  3758.0  2735.0   991.0  5698.0   
12  2020-03-28  17580.0  10400.0  6995.0  4236.0  3105.0  1097.0  6624.0   
13  2020-03-29  19311.0  11470.0  7643.0  4592.0  3397.0  1162.0  7131.0   
14  2020-03-30  20946.0  12457.0  8279.0  5056.0  3756.0  1268.0  7923.0   

     rad.1   rad.2      dc    dc.1    dc.2  
0      1.0     2.0     0.0     1.0     2.0  
1      NaN     NaN     NaN     NaN     NaN  
2    432.0   379.0   218.0   121.0    96.0  
3    580.0   562.0   327.0   179.0   136.0  
4    777.0   764.0   450.0   250.0   190.0  
5    881.0   888.0   525.0   297.0   219.0  
6   1031.0  1040.0   632.0   356.0   263.0  
7   1270.0  1247.0   860.0   497.0   350.0  
8   1609.0  1624.0  1100.0   661.0   425.0  
9   2000.0  2028.0  1388.0   818.0   557.0  
10  2424.0  2456.0  1696.0  1002.0   681.0  
11  2820.0  2806.0  1995.0  1175.0   809.0  
12  3289.0  3251.0  2314.0  1374.0   927.0  
13  3528.0  3516.0  2606.0  1561.0  1032.0  
14  3940.0  3885.0  3024.0  1818.0  1191.0

Afficher les 15 dernières lignes du tableau covid_sexe.csv. (df.tail?)

In [32]:
df.tail(15)

Unnamed: 0     hosp  hosp.1  hosp.2    rea  rea.1  rea.2       rad  \
1096  2023-03-17  13279.0  5982.0  7058.0  755.0  461.0  285.0  858444.0   
1097  2023-03-18  13205.0  5973.0  6995.0  752.0  462.0  282.0  858672.0   
1098  2023-03-19  13211.0  5979.0  6995.0  754.0  463.0  283.0  858680.0   
1099  2023-03-20  13358.0  6052.0  7068.0  760.0  469.0  282.0  859128.0   
1100  2023-03-21  13434.0  6083.0  7109.0  761.0  463.0  289.0  859586.0   
1101  2023-03-22  13418.0  6088.0  7090.0  761.0  469.0  283.0  860128.0   
1102  2023-03-23  13025.0  5912.0  6870.0  739.0  456.0  273.0  860867.0   
1103  2023-03-24  13103.0  5937.0  6917.0  751.0  466.0  275.0  861310.0   
1104  2023-03-25  13038.0  5902.0  6890.0  744.0  463.0  271.0  861538.0   
1105  2023-03-26  13036.0  5903.0  6889.0  746.0  466.0  270.0  861565.0   
1106  2023-03-27  13113.0  5950.0  6923.0  728.0  457.0  263.0  861972.0   
1107  2023-03-28  13178.0  6000.0  6943.0  720.0  452.0  261.0  862458.0   
1108  2023-03-29  13184.0  5989.0  6964.0  734.0  456.0  270.0  862962.0   
1109  2023-03-30  13186.0  5953.0  7003.0  732.0  459.0  267.0  863331.0   
1110  2023-03-31  13149.0  5919.0  6997.0  709.0  446.0  258.0  863837.0   

         rad.1     rad.2        dc     dc.1     dc.2  
1096  419559.0  430886.0  135726.0  77437.0  57233.0  
1097  419653.0  431016.0  135737.0  77441.0  57240.0  
1098  419655.0  431022.0  135737.0  77441.0  57240.0  
1099  419870.0  431252.0  135787.0  77467.0  57264.0  
1100  420088.0  431488.0  135822.0  77489.0  57276.0  
1101  420329.0  431778.0  135835.0  77495.0  57283.0  
1102  420652.0  432187.0  135860.0  77512.0  57291.0  
1103  420874.0  432408.0  135875.0  77521.0  57297.0  
1104  420987.0  432518.0  135889.0  77527.0  57305.0  
1105  420997.0  432534.0  135894.0  77530.0  57307.0  
1106  421189.0  432745.0  135936.0  77555.0  57324.0  
1107  421407.0  433007.0  135975.0  77575.0  57342.0  
1108  421645.0  433268.0  136009.0  77594.0  57356.0  
1109  421833.0  433447.0  136045.0  77609.0  57376.0  
1110  422089.0  433693.0  136076.0  77630.0  57385.0

In [28]:
meta_df = pd.read_csv("1/metadata_covid_sexe.csv", encoding="latin",sep=";")
meta_df

Colonne          Type                                      Description_FR  \
0       dep        integer                                       Département   
1      sexe        integer                                              Sexe    
2      jour  string($date)                              Date de notification    
3      hosp        integer     Nombre de personnes actuellement hospitalisées   
4       rea        integer  Nombre de personnes actuellement en services d...   
5       rad        integer   Nombre cumulé de personnes retournées à domicile   
6        dc        integer    Nombre cumulé de personnes décédées à l'hôpital   
7  ssr_usld        integer  Nombre de personnes actuellement en services d...   
8  hospconv        integer  Nombre de personnes actuellement en services d...   
9   autres         integer  Nombre de personnes actuellement en autres typ...   

                                      Description_EN     Exemple  
0                                         Department           1  
1                                               Sex            0  
2                                     Date of notice  18/03/2020  
3            Number of people currently hospitalized           2  
4  Number of people currently in resuscitation or...           0  
5         Total amount of patient that returned home           1  
6              Total amout of deaths at the hospital           0  
7                                                NaN         NaN  
8                                                NaN         NaN  
9                                                NaN         NaN

Quelle est la période temporelle sur laquelle s'étendent les données ?

-> On commence par sortir les deux premières colonnes du tableau ou sont contenues les dates
-> dates.apply(pd.to_datetime) permet de changer la colonne 2 en format date. Attention, cette fontion ne permet pas de modifier le tableau d'originne. Pour ça on change le tableau avec "dates =...". On pourrais aussi le spécifier avec "inplace = True" en argument.

In [60]:
dates = df[2:]["Unnamed: 0"]

dates = dates.apply(pd.to_datetime)

dates

2      2020-03-18
3      2020-03-19
4      2020-03-20
5      2020-03-21
6      2020-03-22
          ...    
1106   2023-03-27
1107   2023-03-28
1108   2023-03-29
1109   2023-03-30
1110   2023-03-31
Name: Unnamed: 0, Length: 1109, dtype: datetime64[ns]

In [ ]:
-> afficher la date max

In [61]:
dates.max()

Timestamp('2023-03-31 00:00:00')

In [ ]:
-> afficher la date min

In [62]:
dates.min()

Timestamp('2020-03-18 00:00:00')

In [ ]:
calculer le nombre de jour, en soustrayant le max au min

In [71]:
date_range =(dates.max() - dates.min())

date_range.days+1

print("Les donnée s'étalent sur", date_range.days+1, "jours")

Les donnée s'étalent sur 1109 jours


années ?

In [74]:
years_range = 1109/365
print("Les donnée s'étalent sur", int(years_range), "années")

Les donnée s'étalent sur 3 années


Dessiner un Heatmap des corrélations des caractéristiques qui vous semblent pertinentes d'observer ? Discuter les résultats

In [78]:
meta_df

Colonne          Type                                      Description_FR  \
0       dep        integer                                       Département   
1      sexe        integer                                              Sexe    
2      jour  string($date)                              Date de notification    
3      hosp        integer     Nombre de personnes actuellement hospitalisées   
4       rea        integer  Nombre de personnes actuellement en services d...   
5       rad        integer   Nombre cumulé de personnes retournées à domicile   
6        dc        integer    Nombre cumulé de personnes décédées à l'hôpital   
7  ssr_usld        integer  Nombre de personnes actuellement en services d...   
8  hospconv        integer  Nombre de personnes actuellement en services d...   
9   autres         integer  Nombre de personnes actuellement en autres typ...   

                                      Description_EN     Exemple  
0                                         Department           1  
1                                               Sex            0  
2                                     Date of notice  18/03/2020  
3            Number of people currently hospitalized           2  
4  Number of people currently in resuscitation or...           0  
5         Total amount of patient that returned home           1  
6              Total amout of deaths at the hospital           0  
7                                                NaN         NaN  
8                                                NaN         NaN  
9                                                NaN         NaN

In [ ]:
df